#!/bin/sh
set -eu

: "${FRONTEND_LOCAL_API_BASE_URL:=}"
: "${FRONTEND_LOCAL_BACKEND_LABEL:=Local Docker backend}"
: "${FRONTEND_REMOTE_API_BASE_URL:=https://yalla-balagan.fastapicloud.dev}"
: "${FRONTEND_REMOTE_BACKEND_LABEL:=FastAPI Cloud backend}"
: "${FRONTEND_DEFAULT_BACKEND_KEY:=local}"

case "$FRONTEND_DEFAULT_BACKEND_KEY" in
  remote)
    FRONTEND_API_BASE_URL="$FRONTEND_REMOTE_API_BASE_URL"
    FRONTEND_BACKEND_LABEL="$FRONTEND_REMOTE_BACKEND_LABEL"
    ;;
  *)
    FRONTEND_API_BASE_URL="$FRONTEND_LOCAL_API_BASE_URL"
    FRONTEND_BACKEND_LABEL="$FRONTEND_LOCAL_BACKEND_LABEL"
    FRONTEND_DEFAULT_BACKEND_KEY="local"
    ;;
esac

export FRONTEND_API_BASE_URL
export FRONTEND_BACKEND_LABEL

envsubst '${FRONTEND_API_BASE_URL} ${FRONTEND_BACKEND_LABEL} ${FRONTEND_DEFAULT_BACKEND_KEY} ${FRONTEND_LOCAL_API_BASE_URL} ${FRONTEND_LOCAL_BACKEND_LABEL} ${FRONTEND_REMOTE_API_BASE_URL} ${FRONTEND_REMOTE_BACKEND_LABEL}' \
  < /usr/share/nginx/html/config.template.js \
  > /usr/share/nginx/html/config.js
